name: pipeline-environment-dev
version: 1
dependencies:
  - python=3.11
  - pip:
    - cloudpickle==3.0.0
    - contourpy==1.2.1
    - cramjam==2.8.3
    - cycler==0.12.1
    - fastparquet==2024.5.0
    - fonttools==4.53.1
    - fsspec==2024.6.1
    - iniconfig==2.0.0
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - llvmlite==0.43.0
    - matplotlib==3.9.1
    - numba==0.60.0
    - numpy==2.0.0
    - nvidia-nccl-cu12==2.22.3
    - packaging==24.1
    - pandas==2.2.2
    - pillow==10.4.0
    - pluggy==1.5.0
    - pyodbc==5.1.0
    - pyparsing==3.1.2
    - pytest==8.2.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pytz==2024.1
    - scikit-learn==1.5.1
    - scikit-plot==0.3.7
    - scipy==1.14.0
    - seaborn==0.13.2
    - shap==0.46.0
    - six==1.16.0
    - slicer==0.0.8
    - threadpoolctl==3.5.0
    - tqdm==4.66.4
    - tzdata==2024.1
    - xgboost==2.1.0
channels:
  - conda-forge
  - defaults
