$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: paynet_model_training_pipeline
display_name: Paynet Model Training Pipeline
description: Paynet model training pipeline which compares the model with previous version and generates a report
experiment_name: Paynet_Credit_Score_Experiment
tags:
  project: paynet
  area: credit_scoring
  purpose: training
  environment: development
  base_model: paynet_diabetes@latest

# Inputs should be provided by the caller
# default values will cause the pipeline to fail
inputs:
  model_name: xx
  outcome_label_column_name: xx
  split_ratio: xx
  model_selection_criteria: xx

outputs:
  model_eval_report:
    type: uri_file
    mode: upload
  model_comparison_report:
    type: uri_file
    mode: upload
  model_register_report:
    type: uri_file
    mode: upload
  trained_model:
    type: mlflow_model
    mode: upload

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:serverless
  continue_on_step_failure: false

jobs:
  paynet_feature_engineering_step:
    type: command
    component: ./../components/preprocessing/feature_engineering.yaml
    inputs:
      dataset_path:
        type: uri_file
        path: azureml:diabetes@latest
        mode: ro_mount

  split_data_step:
    type: command
    component: ./../components/training/split_data.yaml
    inputs:
      input_data: ${{parent.jobs.paynet_feature_engineering_step.outputs.transformed_data_path}}
      split_ratio: ${{parent.inputs.split_ratio}}

  evaluate_latest_model_step:
    type: command
    component: ./../components/classification/model_evaluator.yaml
    inputs:
      model_id: reference
      outcome_label: ${{parent.inputs.outcome_label_column_name}}
      model_path: 
        type: mlflow_model
        path: azureml:paynet_diabetes@latest
      test_data: ${{parent.jobs.split_data_step.outputs.test_data}}

  paynet_train_model_step:
    type: command
    component: ./../components/training/train_model.yaml
    inputs:
      training_data: ${{parent.jobs.split_data_step.outputs.train_data}}
      outcome_label: ${{parent.inputs.outcome_label_column_name}}
    outputs:
      output_model: ${{parent.outputs.trained_model}}

  evaluate_trained_model_step:
    type: command
    component: ./../components/classification/model_evaluator.yaml
    inputs:
      model_id: trained
      outcome_label: ${{parent.inputs.outcome_label_column_name}}
      model_path: ${{parent.jobs.paynet_train_model_step.outputs.output_model}}
      test_data: ${{parent.jobs.split_data_step.outputs.test_data}}
    outputs:
      result_file: ${{parent.outputs.model_eval_report}}

  compare_current_trained_model_step:
    type: command
    component: ./../components/classification/model_selector.yaml
    inputs:
      model1_report_path: ${{parent.jobs.evaluate_latest_model_step.outputs.result_file}}
      model2_report_path: ${{parent.jobs.evaluate_trained_model_step.outputs.result_file}}
      constraint: ${{parent.inputs.model_selection_criteria}}
    outputs:
      comparison_report: ${{parent.outputs.model_comparison_report}}

  register_model_step:
    type: command
    component: ./../components/training/register_model.yaml
    inputs:
      comparison_report: ${{parent.jobs.compare_current_trained_model_step.outputs.comparison_report}}
      model_name: ${{parent.inputs.model_name}}
      model_id: trained
      trained_model: ${{parent.jobs.paynet_train_model_step.outputs.output_model}}            
    outputs:
      register_report: ${{parent.outputs.model_register_report}}