$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Paynet model training pipeline which compares the model with previous version and generates a report
experiment_name: Paynet_Credit_Score

inputs:
  dataset_name: paynet_source
  model_name: paynet_model
  outcome_label_column_name: label
  split_ratio: 0.7
  model_selection_criteria: balanced

outputs: 
  model_comparison_report:
    mode: upload

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:serverless
  continue_on_step_failure: false

jobs:
  paynet_feature_engineering_step:
    type: command
    component: azureml:paynet_feature_engineering@latest
    inputs:
      dataset_name: ${{inputs.dataset_name}}

  split_data_step:
    type: command
    component: azureml:split_data@latest
    inputs:
      input_data: ${{jobs.paynet_feature_engineering_step.outputs.transformed_data_path}}
      split_ratio: ${{inputs.split_ratio}}

  evaluate_latest_model_step:
    type: command
    component: azureml:classification_model_evaluator@latest
    inputs:
      model_name: ${{inputs.model_name}}
      model_version: latest
      test_data: ${{jobs.split_data_step.outputs.test_data}}
      outcome_label: ${{inputs.outcome_label_column_name}}

 paynet_train_model_step: 
  type: command
    component: azureml:paynet_train_model@latest
    inputs:
      model_name: ${{inputs.model_name}}
      training_data: ${{jobs.split_data_step.outputs.train_data}}

  evaluate_trained_model_step:
    type: command
    component: azureml:classification_model_evaluator@latest
    inputs:
      model_name: ${{inputs.model_name}}
      model_version: ${{jobs.paynet_train_model_step.outputs.model_version}}
      test_data: ${{jobs.split_data_step.outputs.test_data}}
      outcome_label: ${{inputs.outcome_label_column_name}}

  compare_current_trained_model_step:
    type: command
    component: azureml:classification_model_selector@latest
    inputs:
      model1_report_path: ${{jobs.evaluate_latest_model_step.outputs.result_file}}
      model2_report_path: ${{jobs.evaluate_trained_model_step.outputs.result_file}}
      constraint: ${{inputs.model_selection_criteria}}
    outputs:
      comparison_report: ${{outputs.model_comparison_report}}

