name: paynet_train_model
display_name: Paynet - Model Training Component
description: Trains the model based on the training dataset
version: 6
type: command
inputs:
  training_data:
    type: uri_folder
    description: Path to the train dataset in csv format
  outcome_label:
    type: string
    description: Name of the column with the outcome label
outputs:
  output_model:
    type: mlflow_model
    description: Path of the trained model folder
code: .
command: >
  python train_model.py
  --training_data ${{inputs.training_data}}
  --outcome_label ${{inputs.outcome_label}}
  --output_model ${{outputs.output_model}}
environment: azureml:sklearn-dev310@latest
