pr: none
trigger: none

stages:
- stage: "Build"
  displayName: 'Build stage for the branch'
  jobs:
  - job: "Build_and_Test"
    displayName: "Runs the build and unit test"
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 60
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.10'
      inputs:
        versionSpec: '3.10.x'
        addToPath: true
        architecture: 'x64'

    - task: AzureCLI@2
      displayName: 'Install Python dependencies' 
      inputs:
        azureSubscription: 'SPN_DataScience'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript:  |
          source ./.pipelines/pkg-requirements/install.sh
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'SPN_DataScience'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo 'Running unit test cases ...'
          pytest --cov=src --cov-report=html --cov-report=xml --junitxml=junit/test-results.xml ./tests
        workingDirectory: '$(Build.SourcesDirectory)'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'


